print("Hello World")
print("I love to code!")
print("Green")
print("Blue")
print("Yellow")
print("Noodles")
print("Oranges")
print("Milk")
print("Amazing. It was so. With mom. Or dad, maybe both. Prehaps even the best!")
print("Video Games")
print("Swimming")
print("Eating Best Food")
print("Sleeping")
print("Playing Other Games")